export { default as shuffleArray } from "./shuffle";
export { default as sorting} from "./sorting";
export { default as prob} from "./prob";
export { default as geraTab } from "./geraTab";
export { default as printTab } from "./printTab";
export { default as preencheTab } from "./preencheTab";
export { default as checksWord } from "./checksWord";
export { default as crossWord } from "./crossWord";
export { default as resetCrossWords } from "./resetCrossWords";
export { default as handleOnClick } from "./handleOnClick";
export { default as Scorer } from "./scorer";